FROM node:18-alpine AS builder
WORKDIR /app

COPY my-angular-app/package.json my-angular-app/package-lock.json* ./

RUN npm install --legacy-peer-deps

COPY my-angular-app/. ./

RUN npm run build -- --configuration production


FROM nginx:1.25-alpine
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/dist/my-angular-app/browser/ .

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80