FROM eclipse-temurin:21-jdk-jammy AS builder
WORKDIR /workspace/app
COPY gradle gradle
COPY gradlew gradlew.bat ./
COPY build.gradle settings.gradle ./
RUN chmod +x ./gradlew
RUN ./gradlew dependencies --no-daemon
COPY src src
RUN ./gradlew bootJar -x test --no-daemon

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=builder /workspace/app/build/libs/*.jar app.jar
CMD ["java", "-jar", "/app/app.jar"]